# Generated by Django 6.0.5 on 2026-05-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0002_cartitem_cart_unique_user_product_cart_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_user_product_cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
