# Generated by Django 6.0.5 on 2026-05-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='off',
            new_name='discount_off',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='on',
            new_name='discount_on',
        ),
    ]
