# Generated by Django 6.0.5 on 2026-05-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0002_rename_off_discount_discount_off_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_off',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_on',
            field=models.IntegerField(),
        ),
    ]
