# Generated by Django 6.0.5 on 2026-05-12 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0003_alter_discount_discount_off_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='discount_off',
            new_name='discount_amount',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='discount_on',
            new_name='minimum_order_amount',
        ),
        migrations.AddField(
            model_name='discount',
            name='expires_on',
            field=models.DateField(default='2026-12-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='vendor',
            field=models.ForeignKey(default=1983, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='coupon_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
