# Generated by Django 6.0.5 on 2026-05-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0004_rename_discount_off_discount_discount_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='vendor',
            new_name='creator',
        ),
    ]
