# Generated by Django 6.0.5 on 2026-05-19 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0006_remove_discount_expires_on_discount_applicable_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='discount',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='maximum_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='discount',
            name='usage_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='discount',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
