# Generated by Django 6.0.5 on 2026-05-20 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0008_alter_discount_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles': 'vendor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
