# Generated by Django 6.0.5 on 2026-05-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0009_alter_discount_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='applicable_to',
            field=models.CharField(choices=[('all', 'All Products'), ('category', 'Category'), ('product', 'Product')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='discount',
            name='maximum_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
