# Generated by Django 6.0.5 on 2026-05-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0011_alter_discount_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='applicable_to',
            field=models.CharField(choices=[('all', 'All Products'), ('vendor', 'Vendor')], default='all', max_length=20),
        ),
    ]
