# Generated by Django 6.0.5 on 2026-05-21 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0012_alter_discount_applicable_to'),
        ('Products', '0005_product_rating_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_coupons', to='Products.product'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='applicable_to',
            field=models.CharField(choices=[('all', 'All Products'), ('vendor', 'Vendor'), ('product', 'Single Product')], max_length=20),
        ),
    ]
