# Generated by Django 6.0.5 on 2026-05-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0013_discount_product_alter_discount_applicable_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='discount',
            name='minimum_order_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
