# Generated by Django 6.0.5 on 2026-05-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0002_alter_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
