# Generated by Django 6.0.5 on 2026-05-20 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0003_review_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='average_rating',
        ),
    ]
