# Generated by Django 6.0.5 on 2026-05-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0002_warehouse_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
