# Generated by Django 6.0.5 on 2026-05-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0003_delete_warehouse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
