# Generated by Django 6.0.5 on 2026-06-02 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='Authenticate.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('vendor', 'Vendor'), ('customer', 'Customer'), ('courier', 'Courier')], max_length=20, unique=True),
        ),
    ]
