# Generated by Django 6.0.5 on 2026-06-02 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0006_user_active_role_alter_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_role',
        ),
    ]
