# Generated by Django 6.0.5 on 2026-05-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_product_image'),
        ('Warehouses', '0002_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='products',
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('warehouse', 'product')},
        ),
    ]
