# Generated by Django 6.0.5 on 2026-05-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouses', '0004_stockmovement_alter_inventory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('damage', 'Damage')], max_length=100),
        ),
    ]
