# Generated by Django 6.0.5 on 2026-05-25 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouses', '0005_alter_stockmovement_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('damage', 'Damage'), ('manual_add', 'Manual Add'), ('manual_remove', 'Manual Remove'), ('order', 'Order')], max_length=100),
        ),
        migrations.CreateModel(
            name='StaffWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouses.warehouse')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('staff', 'warehouse'), name='unique_staff_warehouse')],
            },
        ),
    ]
