# Generated by Django 6.0.5 on 2026-06-11 05:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Couriers', '0001_initial'),
        ('Reviews', '0007_rename_courier_person_courierreview_courier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courier',
            new_name='CourierProfile',
        ),
    ]
