# Generated by Django 6.0.5 on 2026-05-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_orderitem_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
