# Generated by Django 6.0.5 on 2026-05-21 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_remove_orderitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount_amount',
            new_name='discounted_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Order.orderaddress'),
        ),
    ]
