# Generated by Django 6.0.5 on 2026-05-16 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Order.orderaddress'),
        ),
    ]
