# Generated by Django 6.0.5 on 2026-05-21 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_rename_discount_amount_order_discounted_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discounted_price',
            new_name='discount_amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.orderaddress'),
        ),
    ]
