# Generated by Django 6.0.5 on 2026-05-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_rename_discounted_price_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending courier assignment', 'Pending courier assignment'), ('pending pickup', 'Pending pick up'), ('arrived for pickup', 'Arrived for pickup'), ('on the way', 'On the way'), ('arrived for delivery', 'Arrived for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='confirmed', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending courier assignment', 'Pending courier assignment'), ('pending pickup', 'Pending pick up'), ('arrived for pickup', 'Arrived for pickup'), ('on the way', 'On the way'), ('arrived for delivery', 'Arrived for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='confirmed', max_length=50),
        ),
    ]
