# Generated by Django 6.0.5 on 2026-05-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_product_average_rating_product_total_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
