# Generated by Django 6.0.5 on 2026-05-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_product_rating_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating_sum',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_reviews',
        ),
    ]
